dist: trusty
sudo: required

addons:
  apt:
    sources:
    - deadsnakes
    - sourceline: 'ppa:wpilib/toolchain'
    packages:
    - frc-toolchain
    - build-essential
    - cmake


before_script:
 - git clone https://github.com/managra/travis_wpilib_mirror.git ~/wpilib

script:
 - make all
 
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a7107a3684b2e894dace
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
